### ISSUE TITLE
Can't install trough npm

### ISSUE THREAD

**Issue by alebertz** [Fazendaaa/tiny-shortener#4]
npm ERR! path /root/OffersBot/node_modules/tiny-shortener/dist/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/root/OffersBot/node_modules/tiny-shortener/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-03T20_32_01_027Z-debug.log

**Comment by sayanriju** [comment]
+1. Same problem here.

**Comment by smitti24** [comment]
+1. Same here

**Comment by bigmarkoberg** [comment]
Same

**Comment by Fazendaaa** [comment]
@MegaITA, @sayanriju, @smitti24 and @bigmarkoberg, fixed. Sorry, it was my bad not configuring the CLI option to work with WEBPACK; it will be published later in a new package.
